# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfmw6LlLuRszunI3lMMluc0UQKeSbY8J
"""

import os

from flask import Flask, request, abort

from linebot.v3 import WebhookHandler
from linebot.v3.exceptions import InvalidSignatureError
from linebot.v3.webhooks import MessageEvent, TextMessageContent
from linebot.v3.messaging import (
    Configuration,
    ApiClient,
    MessagingApi,
    ReplyMessageRequest,
    TextMessage, StickerMessage, ImageMessage, VideoMessage, LocationMessage
)

app = Flask(__name__)

configuration = Configuration(access_token=userdata.get('LINE_CHANNEL_ACCESS_TOKEN'))
handler = WebhookHandler(userdata.get('LINE_CHANNEL_SECRET'))


@app.route("/callback", methods=['POST'])
def callback():
    # get X-Line-Signature header value
    signature = request.headers['X-Line-Signature']

    # get request body as text
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)

    # handle webhook body
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        app.logger.info("Invalid signature. Please check your channel access token/channel secret.")
        abort(400)

    return 'OK'

import google.generativeai as genai

genai.configure(api_key=userdata.get('GOOGLE_API_KEY'))
model = genai.GenerativeModel("gemini-2.0-flash")
def ask_gemini(question):
  response = model.generate_content(question)
  return response.text


@handler.add(MessageEvent, message=TextMessageContent)
def handle_message(event):
    with ApiClient(configuration) as api_client:
        line_bot_api = MessagingApi(api_client)

        action = event.message.text
        if action == 'sticker':
          #回覆貼圖
          reply = StickerMessage(
            package_id='446',
            sticker_id='1989'
          )
        elif action == 'image':
          #回覆圖片
          reply = ImageMessage(
            original_content_url='https://m.gxgif.com/pic/kb/20235141008.jpg',
            preview_image_url='https://m.gxgif.com/pic/kb/20235141008.jpg'
          )
        elif action == 'video':
          #回覆影片
          reply = VideoMessage(
            original_content_url='https://youtu.be/U9Z9X_YXaNY?si=VRH1K7FAuK9vNa3r',
            preview_image_url='https://images.chinatimes.com/newsphoto/2014-10-10/1024/20141010001764.jpg'
          )
        elif action == 'location':
          #回覆位置
          reply = LocationMessage(
            title="台北101",
            address="110台北市信義區信義路五段7號",
            latitude=2.17403,
            longitude=41.40338
          )
        else:
          response = ask_gemini(action)
          reply = TextMessage(text=response)

        line_bot_api.reply_message(
            ReplyMessageRequest(
                reply_token=event.reply_token,
                messages=[reply]
            )
        )

# for colab
ngrok_start()
if __name__ == "__main__":
    app.run()
